# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PGVDSG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from bitmanipulation import BitManipulation
from client import Client

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.cl = 0
        self.dm = 0
        self.t = 0
        self.x_data = 0
        self.y_data = 0
        self.angle_data = 0
        self.a = 0
        self.b = 0
        self.c = 0
        self.d = 0
        self.e = 0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 831, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(500, 250, 47, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(630, 240, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(630, 190, 113, 20))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 361, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/aloks/OneDrive/Desktop/Capture.PNG"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(510, 190, 91, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(500, 330, 261, 51))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 60, 71, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 160, 71, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(-4, -8, 871, 611))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/aloks/OneDrive/Desktop/main.PNG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(160, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(250, 140, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(160, 170, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(250, 170, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(410, 50, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(460, 50, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(160, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(250, 200, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(160, 230, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(260, 230, 47, 13))
        self.label_16.setObjectName("label_16")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 340, 181, 81))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_5.setGeometry(QtCore.QRect(490, 340, 181, 81))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 47, 13))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.clickcon)
        self.pushButton_2.clicked.connect(self.pos)
        self.pushButton_3.clicked.connect(self.img)
        self.pushButton_4.clicked.connect(self.clickdata)
        self.pushButton_5.clicked.connect(self.pos_update)

    def pos(self):
        self.stackedWidget.setCurrentIndex(2)

    def img(self):
        self.stackedWidget.setCurrentIndex(3)

    def clickcon(self):
        self.stackedWidget.setCurrentIndex(1)
        self.cl = Client()
        self.dm = BitManipulation()

    def clickdata(self):
        self.td = str(self.cl.output())[2:4]
        self.x_data = str(self.cl.output())[4:12]
        self.y_data = str(self.cl.output())[12:16]
        self.angle_data = str(self.cl.output())[16:20]

        print(self.dm.tag_data(self.td))
        print(self.dm.x_pos(self.x_data))
        print(self.dm.y_pos(self.y_data))
        print(self.dm.angle_value(self.angle_data))
        print(self.dm.angle_degree(self.angle_data))

        self.a = "True"
        self.b = self.dm.x_pos(self.x_data)
        self.c = self.dm.y_pos(self.y_data)
        self.d = self.dm.angle_value(self.angle_data)
        self.e = self.dm.angle_degree(self.angle_data)
        self.update()

    def pos_update(self):
        self.label_12.setText(self.a)
        self.label_8.setText(str(self.b))
        self.label_10.setText(str(self.c))
        self.label_14.setText(str(self.d))
        self.label_16.setText(str(self.e))
        self.update()

    def update(self):
        self.label_12.adjustSize()
        self.label_8.adjustSize()
        self.label_10.adjustSize()
        self.label_14.adjustSize()
        self.label_16.adjustSize()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "PORT"))
        self.label.setText(_translate("MainWindow", "IP ADDRESS"))
        self.pushButton.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_2.setText(_translate("MainWindow", "Position"))
        self.pushButton_3.setText(_translate("MainWindow", "Image"))
        self.label_5.setText(_translate("MainWindow", "Position"))
        self.label_7.setText(_translate("MainWindow", "X-Postion"))
        self.label_8.setText(_translate("MainWindow", "x"))
        self.label_9.setText(_translate("MainWindow", "Y-Postion"))
        self.label_10.setText(_translate("MainWindow", "y"))
        self.label_11.setText(_translate("MainWindow", "TAG"))
        self.label_12.setText(_translate("MainWindow", "t"))
        self.label_13.setText(_translate("MainWindow", "Angle Value"))
        self.label_14.setText(_translate("MainWindow", "a"))
        self.label_15.setText(_translate("MainWindow", "Angle Degree"))
        self.label_16.setText(_translate("MainWindow", "d"))
        self.pushButton_4.setText(_translate("MainWindow", "GET DATA"))
        self.pushButton_5.setText(_translate("MainWindow", "GET POS"))
        self.label_6.setText(_translate("MainWindow", "Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
